default: &default
  adapter: postgresql
  encoding: unicode
  username: ecommerce_website_user
  password: ecommerce_website_password
  host: localhost
  port: 5432

development:
  <<: *default
  database: ecommerce_website_development

test:
  <<: *default
  database: ecommerce_website_test

production:
  <<: *default
  database: ecommerce_website_production
